### PR TITLE
Updates for the latest endpoints

### LINKED ISSUE #16: Listing->delete() has no effect
Hello!
I've been loving this SDK, it's been a breeze to upgrade my etsy app from the v2 version to v3. 

Recently I was testing out listing functionality and wanted to delete a listing. 

  $listing = $etsy->getListing($listing_id);
  $listing->delete();
  
I know I successfully grabbed the listing and have appropriate scopes, but the listing->delete() call did not work (the listing was still on etsy after the call) and the call did not throw any exceptions. Other functions that I've tested so far like listing->getFiles() works.

Any ideas?

### PR DESCRIPTION
**Pull request by emergingdzns**
@rhysnhall I was one of the developers that helped to build the Etsy OpenAPI V3. I've applied some updates to your package here, including some of the newer functions as well as adjusting to some of the updates we made at Etsy. I am not with Etsy anymore but I'm working for an integrator and found this great package. I haven't had a chance to test all of these so I'm thinking it might be good to pull this to a dev branch for others to evaluate and test. If you create a different branch, I'm happy to redo this PR so you can pull into that branch.

### CODE REVIEW

**Comment by rhysnhall** [comment]
Thanks for submitting this. I haven't been entirely active on this project for a while but I will review it as soon as possible.

**Comment by kopachlager** [comment]
> @rhysnhall I was one of the developers that helped to build the Etsy OpenAPI V3. I've applied some updates to your package here, including some of the newer functions as well as adjusting to some of the updates we made at Etsy. I am not with Etsy anymore but I'm working for an integrator and found this great package. I haven't had a chance to test all of these so I'm thinking it might be good to pull this to a dev branch for others to evaluate and test. If you create a different branch, I'm happy to redo this PR so you can pull into that branch.

Hi, is there any way to contact you related this package. We have some issues related to proper integration and oAuth process with Etsy for our app?
Thanks in advance

**Comment by rhysnhall** [comment]
@emergingdzns thanks for this. Great additions/fixes and will merge this afternoon.

**Comment by rhysnhall** [comment]
This has been merged with some minor fixes.

**Pull request merged**
